version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - opensynthetics_data:/data/opensynthetics
    environment:
      - OPENSYNTHETICS_ENV=prod
      - OPENSYNTHETICS_DATA_DIR=/data/opensynthetics
      # Add your API keys here or use environment variables
      # - OPENAI_API_KEY=${OPENAI_API_KEY}
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  datasette:
    build:
      context: .
      dockerfile: Dockerfile.datasette
    ports:
      - "8001:8001"
    volumes:
      - opensynthetics_data:/data/opensynthetics
    command: >
      datasette serve 
      --host 0.0.0.0 
      --port 8001 
      --cors 
      --metadata /data/opensynthetics/datasette-metadata.json 
      /data/opensynthetics
    restart: unless-stopped
    depends_on:
      - api

volumes:
  opensynthetics_data: