FROM python:3.12-slim

WORKDIR /app

# Install Datasette and plugins
RUN pip install --no-cache-dir datasette~=0.64.5 datasette-vega~=0.6.2 datasette-export-notebook~=0.3.0

# Create directories
RUN mkdir -p /data/opensynthetics

# Environment variables
ENV OPENSYNTHETICS_DATA_DIR=/data/opensynthetics

# Expose port
EXPOSE 8001

# Run Datasette server
CMD ["datasette", "serve", "--host", "0.0.0.0", "--port", "8001", "--cors", "/data/opensynthetics"]